# Generated by Django 4.2 on 2023-04-12 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wolaita sodo', 'Wolaita Sodo'), ('otona', 'Otona'), ('kawo sana', 'Kawo Sana')], max_length=50, unique=True)),
                ('phone', models.CharField(default='04xxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
                ('phone1', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
                ('phone2', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
                ('phone3', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
                ('phone4', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('branch', models.CharField(choices=[('wolaita sodo', 'Wolaita Sodo'), ('otona', 'Otona'), ('kawo sana', 'Kawo Sana')], max_length=50)),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('customer service manager', 'Customer Service Manager'), ('operation manager', 'Operation Manager'), ('digital officer', 'Digital Officer'), ('internal control manager', 'Internal Control Manager'), ('business manager', 'Business Manager')], default='Manager', max_length=100)),
                ('m_phone', models.CharField(default='04xxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
                ('m_phone1', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
                ('m_phone2', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
                ('m_phone3', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number incorrect. it should start +251 format', regex='^\\+?251?\\d{9}$')])),
            ],
        ),
    ]
